"""
Configuration settings and Launchpad Mini MK3 constants.
"""

# MIDI device constants for Launchpad Mini MK3
DEVICE_NAME_KEYWORDS = ["Launchpad Mini MK3", "LPMiniMK3", "Launchpad"]

# SysEx header for Novation Launchpad Mini MK3
# Header: F0 00 20 29 02 0D
SYSEX_HEADER = [0xF0, 0x00, 0x20, 0x29, 0x02, 0x0D]
SYSEX_FOOTER = [0xF7]

# Modes
MODE_PROGRAMMER = SYSEX_HEADER + [0x0E, 0x01] + SYSEX_FOOTER
MODE_LIVE = SYSEX_HEADER + [0x0E, 0x00] + SYSEX_FOOTER

# Color Palettes (Velocity values for Launchpad Mini MK3 palette)
COLOR_OFF = 0
COLOR_GREY_DIM = 1
COLOR_GREY = 2
COLOR_WHITE = 3
COLOR_RED_DIM = 5
COLOR_RED = 6
COLOR_RED_BRIGHT = 7
COLOR_ORANGE = 9
COLOR_YELLOW_DIM = 12
COLOR_YELLOW = 13
COLOR_YELLOW_BRIGHT = 15
COLOR_GREEN_DIM = 17
COLOR_GREEN = 21
COLOR_GREEN_BRIGHT = 25
COLOR_CYAN = 37
COLOR_BLUE = 45
COLOR_PURPLE = 53
COLOR_MAGENTA = 57

# Task State Colors
TASK_COLOR_PENDING = COLOR_GREY_DIM
TASK_COLOR_ACTIVE = COLOR_YELLOW_BRIGHT
TASK_COLOR_SUCCESS = COLOR_GREEN_BRIGHT
TASK_COLOR_ERROR = COLOR_RED_BRIGHT

# Daemon network/socket configuration
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9876
